---
use_cases:
- name: cycloid-common
  sections:
  - name: Registry
    groups:
    - name: Common
      technologies: [pipeline]
      vars:
      - name: "Image Name"
        description: "Name of the repository image. If using AWS ECR you only need the repository name, not the full URI e.g. `alpine` not `012345678910.dkr.ecr.us-east-1.amazonaws.com/alpine`. And for GCP Artifact Registry use `gcr.io/project/repo`"
        key: registry_image_nameeeeeee
        type: string
        default: "myuser/imagename"
        widget: simple_text
        required: true

- name: default2
  sections:
  - name: Registry
    groups:
    - name: Type
      technologies: [pipeline]
      vars:
      - name: "Push to Docker Hub"
        key: docker_hub
        type: boolean
        widget: switch
        default: false
- name: github-pr2
  sections:
  - name: Code
    groups:
    - name: Access
      technologies: [pipeline]
      vars:
      - name: "Github Access Token"
        description: "Github access token with repository access."
        key: code_github_access_token
        type: string
        default: "(((custom_github.access_token))"
        widget: cy_cred
        required: true
