---
use_cases:
- name: cycloid-common
  sections:
  - name: Registry
    groups:
    - name: Common
      technologies: [pipeline]
      vars:
      - name: "COUCOUUUUUUUUU"
        key: registry_image_nameeeeeee
        type: string
        default: "myuser/imagename"
        widget: simple_text
        required: true

- name: default2
  sections:
  - name: Registry
    groups:
    - name: Type
      technologies: [pipeline]
      vars:
      - name: "Push to Docker Hub"
        key: docker_hub
        type: boolean
        widget: switch
        default: false
- name: github-pr2
  sections:
