shared:
  # Task : sync and merge with rsync 2 rep. Used to merge stack and config
  - &merge-stack-and-config
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: cycloid/cycloid-toolkit
        tag: latest
    #run:
    #  path: /usr/bin/merge-stack-and-config
    run:
      path: /bin/sh
      args:
      - -c
      - |
        /usr/bin/merge-stack-and-config
        echo rc-$(cat config/.git/short_ref) > merged-stack/TAGS-RC
        echo ${EXTRA_TAGS} $(cat config/.git/short_ref) > merged-stack/TAGS
        if [ -n "BUILD_ARGS" ]; then
          python -c "import json, os, yaml; print('\n'.join([ '%s=%s' % (k,v) for k, v in json.loads(os.environ['BUILD_ARGS'].replace('\\n','\\\\\\\n')).items()]))" >> merged-stack/build_args_file
          cat merged-stack/build_args_file
        fi
    outputs:
      - name: merged-stack
        path: "merged-stack"

resource_types:

- name: registry-image
  type: registry-image
  privileged: true
  source:
    repository: concourse/registry-image-resource
    tag: latest

resources:

- name: image
  type: registry-image
  source:
    #version: every
    repository: ((registry_image_name))
    username: ((registry_username))
    password: ((registry_password))
    tag: ci-rc


- name: git_stack
  type: git
  check_every: 2m
  source:
    #uri: https://github.com/cycloid-community-catalog/stack-magento
    branch: ((stack_git_branch))
# TODO : replace it by the public stack
    uri: git@github.com:cycloidio/cycloid-stacks.git
    private_key: ((code_git_private_key))
    paths:
      - stack-dockerbuild/docker/*

- name: git_code
  type: git
  check_every: 2m
  source:
    uri: ((code_git_repository))
    branch: ((code_git_branch))
    private_key: ((code_git_private_key))
    paths:
      - ((code_build_context))/*

jobs:

- name: tests
  build_logs_to_retain: 3
  plan:

  - aggregate:
    - get: git_stack
      trigger: true
    - get: git_code
      trigger: true

  - task: merge-stack-and-config
    config:
      <<: *merge-stack-and-config
      inputs:
      - name: git_code
        path: "config"
      - name: git_stack
        path: "stack"
    params:
      CONFIG_PATH: ((code_build_context))
      STACK_PATH: stack-dockerbuild/docker
      EXTRA_TAGS: ((registry_extra_tags))
      BUILD_ARGS: ((code_build_args))

  - task: tests
    file: merged-stack/tests.yml
    privileged: true

- name: build-rc
  build_logs_to_retain: 3
  plan:

  - aggregate:
    - get: git_stack
      trigger: true
      passed:
      - tests
    - get: git_code
      trigger: true
      passed:
      - tests

  - task: merge-stack-and-config
    config:
      <<: *merge-stack-and-config
      inputs:
      - name: git_code
        path: "config"
      - name: git_stack
        path: "stack"
    params:
      CONFIG_PATH: ((code_build_context))
      STACK_PATH: stack-dockerbuild/docker
      EXTRA_TAGS: ((registry_extra_tags))
      BUILD_ARGS: ((code_build_args))

  - task: build
    file: merged-stack/build.yml
    privileged: true
    params:
      REPOSITORY: ((registry_image_name))
      CONTEXT: merged-stack
      DOCKERFILE: merged-stack/((code_dockerfile_location))
      BUILD_ARGS_FILE: merged-stack/build_args_file

  - put: image
    params:
      additional_tags: merged-stack/TAGS-RC
      image: image/image.tar


- name: post-tests
  build_logs_to_retain: 3
  plan:

  - aggregate:
    - get: git_stack
      trigger: false
      passed:
      - build-rc
    - get: git_code
      trigger: false
      passed:
      - build-rc
    - get: image
      passed:
      - build-rc
      trigger: true
      params:
        format: oci

  - task: merge-stack-and-config
    config:
      <<: *merge-stack-and-config
      inputs:
      - name: git_code
        path: "config"
      - name: git_stack
        path: "stack"
    params:
      CONFIG_PATH: ((code_build_context))
      STACK_PATH: stack-dockerbuild/docker
      EXTRA_TAGS: ((registry_extra_tags))
      BUILD_ARGS: ((code_build_args))

  - task: post-tests
    file: merged-stack/post-tests.yml
    privileged: true
    params:
      REPOSITORY: ((registry_image_name))

- name: push
  build_logs_to_retain: 3
  plan:

  - aggregate:
    - get: git_stack
      trigger: false
      passed:
      - post-tests
    - get: git_code
      trigger: false
      passed:
      - post-tests
    - get: image
      passed:
      - post-tests
      trigger: true
      params:
        format: oci

  - task: merge-stack-and-config
    config:
      <<: *merge-stack-and-config
      inputs:
      - name: git_code
        path: "config"
      - name: git_stack
        path: "stack"
    params:
      CONFIG_PATH: ((code_build_context))
      STACK_PATH: stack-dockerbuild/docker
      EXTRA_TAGS: ((registry_extra_tags))
      BUILD_ARGS: ((code_build_args))

  - put: image
    params:
      additional_tags: merged-stack/TAGS
      image: image/image.tar
