---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cycloid/cycloid-toolkit
    tag: latest
run:
  path: /bin/echo
  args:
    - "###### No tests configured"
inputs:
- name: merged-stack
